services:
  - type: web
    name: awwaludevs-backend
    runtime: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      gunicorn app:app -c gunicorn.conf.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://awwalu_devs_user:g9H6aR0008qZC1n7SX5PQXy0Hria1Fjz@dpg-d9sdick9v7es73emm6tg-a.ondigitalocean.com:5432/awwalu_devs_db?sslmode=require
      - key: FLASK_DEBUG
        value: False
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.11.0